spring:
  datasource:
    url: jdbc:mysql://localhost:3306/filemanage + ?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8081
